main:
  build: router/.
  links:
    - acm
    - hackathon
  ports:
    - "25:25"
    - "127.0.0.1:8008:8008"

acm:
  build: mailman/.
  dockerfile: acm.dockerfile
  volumes_from:
    - acm-email-data

hackathon:
  build: mailman/.
  dockerfile: hackathon.dockerfile
  volumes_from:
    - hackathon-email-data

