main:
  build: proxy/.
  links:
    - acm
    - hackathon
  ports:
    - "25:25"
    - "8080:8080"

acm:
  build: mailman/.
  dockerfile: acm.dockerfile
  volumes_from:
    - acm-email-data

hackathon:
  build: mailman/.
  dockerfile: hackathon.dockerfile
  volumes_from:
    - hackathon-email-data

